In [2]:
import numpy as np
vector = np.array([10, 20, 30])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [3]:
vector_shape = vector.shape
matrix_shape = matrix.shape
print(vector_shape)
print(matrix_shape)

(3,)
(3, 3)


In [ ]:
# world_alcohol= numpy.genfromtxt("world_alcohol.csv", delimiter=",") podemos ler csv tbm
# world_alcohol= numpy.genfromtxt("world_alcohol.csv", delimiter=",",skip_header = 1 , dtype = "U75") Podemos passar como parametro
# skipheader pra pular o header, "u75" ler unicode 75